pirulin = [ball : cg 0 : cr 0.5] & [pirulin : tx 1 : cr 1.2 : s 0.9]

"Recursion inside recursion"
yodawg = box & [pirulin : d 10 : rz 90 : ty 1] & [yodawg : tx 2]

spiral = ball &
         [pirulin : rz -90 : ty -1 : d 5] &
         [spiral : tx 1 : rz 15 : s 0.9]

$ = [ball : cr 0 : cb 0 : s 0.25] &
    [pirulin : d 25 : ty 5] &
    [spiral : d 25 : tx 2 : ty -2] &
    [yodawg : s 0.5 : rz 90 : tx -2 : ty -10]

